### ISSUE TITLE
do not recommend spinning in a loop in 

### ISSUE THREAD

**Issue by matu3ba** [tr1ckydev/zig_guides#1]
`while (true) {}` is not good. https://github.com/tr1ckydev/zig_guides/blob/main/guides/process/listen_for_ctrl_c.zig
Use the zig sleep call (typically >=20us on Kernels independent on what the syscall description says, ie if it says nanoseconds it lies).

**Comment by Atomk** [comment]
Since it's a guide and using `while` is probably the more popular choice, I would add a comment explaining why using `sleep` is better.
